name = "SpinSim"
author = ["Javier Norambuena"]
version = "0.1.0"
uuid="a9872f58-4f48-11ef-0c06-ff7f93bd3947"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
julia = "1.10"
